### ISSUE TITLE
Nvidia Quadro M3000M fails to start

### ISSUE THREAD

**Issue by SpookySkeletons** [BlueGoliath/GoliathOUFX#1]
Hello, I went to try Goliath on my M3000M card with coolbits 31, this was the result in terminal.

Application start
InstanceProvider: Found GPU Quadro M3000M with ID GPU-0
InstanceProvider: API providing 20 attributes for primary GPU Quadro M3000M:
<DISPLAY-ATTRIBUTE(CMD-ATTRIBUTE)>:<CURRENT_VALUE>:<OPERATIONALSTATUS>
        GPU Name(GPU-0):Quadro M3000M:Read Only
        GPU Branding(N/A):N/A:Read Only
        GPU SubBranding(N/A):N/A:Read Only
        GPU Family(N/A):UNKNOWN:Read Only
        GPU Core Clock(GPUCurrentClockFreqs):822:Read Only
        GPU Clock Offset(GPUGraphicsClockOffset):0:Readable and Controllable
        GPU Core Usage(GPUUtilization):1:Read Only
        GPU Core Temperature(GPUCoreTemp):44:Read Only
        GPU Current Voltage(GPUCurrentCoreVoltage):1200000:Read Only
        GPU Voltage Offset(GPUOverVoltageOffset):0:Readable and Controllable
        GPU Fan Mode(GPUFanControlState):Auto:Readable and Controllable
        GPU Memory Clock(GPUCurrentClockFreqs):2505:Read Only
        GPU Memory Clock Offset(GPUMemoryTransferRateOffset):0:Readable and Controllable
        GPU Memory Bandwidth Usage(GPUUtilization):1:Read Only
        GPU Used Memory(UsedDedicatedGPUMemory):643:Read Only
        GPU Logo Brightness(GPULogoBrightness):0:Readable and Controllable
        GPU UUID(GpuUUID):GPU-1cfd257b-91cf-e195-8511-c1910ea52aa7:Read Only
        GPU Performance Modes(GPUPerfModes):[ZERO, ONE, TWO, THREE]:Read Only
        GPU PowerMizer Mode(GPUPowerMizerMode):Adaptive:Readable and Controllable
        GPU Current Performance Level(GPUCurrentPerfLevel):3:Read Only
Launch application GUI
Exception in Application start method
Safe shutdown not achieved! Setting ALL GPU controllers to their default values!
Application shutdown.

**Exception in Application start method**
Any sort of log I can post to make this bit more helpful?

I am running Arch linux.

**Comment by BlueGoliath** [comment]
I've never tested it with a Quadro, sadly. 

Try [this](https://github.com/BlueGoliath/GoliathOUFX/releases/tag/V3-Dev) version and if it still doesn't work, post the output.

Also, could you post the output of:

nvidia-smi
nvidia-smi -q -d PERFORMANCE 
nvidia-smi -q -d POWER

**Comment by SpookySkeletons** [comment]
The dev version drops

Application start
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.ExceptionInInitializerError
        at goliathoufx/goliathoufx.APIDumper.dump(APIDumper.java:13)
        at goliathoufx/goliathoufx.GoliathOUFX.main(GoliathOUFX.java:70)
        ... 11 more
Caused by: java.lang.NullPointerException
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:543)
        at goliath.nvsettings/goliath.nvsettings.attribute.gpu.NvVoltageOffsetAttribute.update(NvVoltageOffsetAttribute.java:132)
        at goliath.nvsettings/goliath.nvsettings.attribute.gpu.NvVoltageOffsetAttribute.<init>(NvVoltageOffsetAttribute.java:110)
        at goliath.nvsettings/goliath.nvsettings.targets.NvGPU.<init>(NvGPU.java:142)
        at goliath.nvsettings/goliath.nvsettings.targets.NvGPU.createNvGPU(NvGPU.java:110)
        at goliath.nvsettings/goliath.nvsettings.targets.shim.NvGPUShim.creatNewNvGPU(NvGPUShim.java:10)
        at goliath.nvsettings/goliath.nvsettings.main.NvSettings.initGPUList(NvSettings.java:95)
        at goliath.nvsettings/goliath.nvsettings.main.NvSettings.getGPU(NvSettings.java:61)
        at goliath.nvsettings/goliath.nvsettings.main.NvSettings.<clinit>(NvSettings.java:25)
        ... 13 more
Exception running application goliathoufx.GoliathOUFX


Funny. Version 1.04 works like it should.

nvidia-smi

Wed Nov 14 01:28:14 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54.09              Driver Version: 396.54.09                 |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro M3000M       Off  | 00000000:01:00.0  On |                  N/A |
| N/A   57C    P0    24W /  75W |    686MiB /  4040MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       979      G   /usr/lib/Xorg                                290MiB |
|    0      1486      G   /usr/bin/kwin_x11                             71MiB |
|    0      1492      G   /usr/bin/krunner                              29MiB |
|    0      1494      G   /usr/bin/plasmashell                          89MiB |
|    0     22020      G   /usr/bin/firefox                              79MiB |
|    0     29209      G   ****************************   102MiB |
+-----------------------------------------------------------------------------+

 nvidia-smi -q -d PERFORMANCE

==============NVSMI LOG==============

Timestamp                           : Wed Nov 14 01:28:40 2018
Driver Version                      : 396.54.09

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : N/A
            HW Power Brake Slowdown : N/A
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active

 nvidia-smi -q -d POWER

==============NVSMI LOG==============

Timestamp                           : Wed Nov 14 01:29:08 2018
Driver Version                      : 396.54.09

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Power Readings
        Power Management            : Supported
        Power Draw                  : 24.14 W
        Power Limit                 : 75.00 W
        Default Power Limit         : 75.00 W
        Enforced Power Limit        : 75.00 W
        Min Power Limit             : 0.00 W
        Max Power Limit             : 75.00 W
    Power Samples
        Duration                    : 2.36 sec
        Number of Samples           : 119
        Max                         : 25.61 W
        Min                         : 23.57 W
        Avg                         : 24.59 W

**Comment by SpookySkeletons** [comment]
Well, this is weird.
I'd like to test for you but...

Your link is broken and now V1.04 binary that I just had working is throwing

Nov 14, 2018 8:10:49 PM goliath.nvsettings.main.NvSettings initGPUList
SEVERE: null
goliath.nvsettings.exceptions.InvalidAttributeException: Unknown Nvidia attribute!
        at goliath.nvsettings/goliath.nvsettings.attribute.NvAttributePuller.getAttributeValueList(NvAttributePuller.java:60)
        at goliath.nvsettings/goliath.nvsettings.main.NvSettings.initGPUList(NvSettings.java:79)
        at goliath.nvsettings/goliath.nvsettings.main.NvSettings.getGPU(NvSettings.java:57)
        at goliath.nvsettings/goliath.nvsettings.main.NvSettings.<clinit>(NvSettings.java:23)
        at goliathoufx/goliathoufx.InstanceProvider.init(InstanceProvider.java:54)
        at goliathoufx/goliathoufx.GoliathOUFX.main(GoliathOUFX.java:69)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)

java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.ExceptionInInitializerError
        at goliathoufx/goliathoufx.InstanceProvider.init(InstanceProvider.java:54)
        at goliathoufx/goliathoufx.GoliathOUFX.main(GoliathOUFX.java:69)
        ... 11 more
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:458)
        at goliath.nvsettings/goliath.nvsettings.main.NvSettings.getGPU(NvSettings.java:59)
        at goliath.nvsettings/goliath.nvsettings.main.NvSettings.<clinit>(NvSettings.java:23)
        ... 13 more
Exception running application goliathoufx.GoliathOUFX

**Comment by SpookySkeletons** [comment]
Nvidia-smi allows me to set a very slight >0 setting but not =0.

It still seems to pull as much power as it needs but it dropped my idle usage to about 10 watts from 25, so that's neat. Only on AC, battery already nets good savings.

**Comment by BlueGoliath** [comment]
If you try to run the app after doing any graphics driver update it will fail since the driver is left in some wonky state, which is likely what happened as that error was caused by nvidia-settings failing to return a list of GPUs.

Also, [this](https://github.com/BlueGoliath/GoliathOUFX/releases/tag/V3-Dev) link should work. If not, just go to the releases section and download it.

**Comment by SpookySkeletons** [comment]
Works perfectly, thank you!
